package com.openbanking.enums;

public enum TransactionStatus {
    RECONCILING, AWAITING_RECONCILIATION, COMPLETED_RECONCILIATION, FAILED_RECONCILIATION, MATCHED_RECONCILIATION, UNMATCHED_RECONCILIATION
}
