spring:
  application:
    name: openbanking
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://10.0.0.101:5432/open_banking_db?currentSchema=public}
    username: ${SPRING_DATASOURCE_USERNAME:open_banking_user}
    password: ${SPRING_DATASOURCE_PASSWORD:Apec@2024}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    hikari:
      schema: ${SPRING_DATASOURCE_HIKARI_SCHEMA:public}
  jpa:
    show-sql: true


